### ISSUE TITLE
HTML output contains double slashes

### ISSUE THREAD

**Issue by petermnt** [bmw-tech/ozzie.flutter#43]
The index.html output contains a double slash in the image references.

For example `.//group/timestamp-test.png`
This works on the local system but doesn't work online (at least not on AWS S3.

The `images` array already contains a preceding `/`, so I stripping the `/` while stripping the default dir.

I implemented it in our fork at https://github.com/vrtdev/ozzie.flutter/commit/db8f84dcf01ce9ee404101abb08727cbc23f3e5c and could open a PR if this solution seems fine.

**Comment by jorgecoca** [comment]
Please feel free to open a PR with a fix for this issue ;)

**Comment by petermnt** [comment]
Fixed in #45
